##
# CONTEXT PATH
##
server:
  port: 8081
  servlet:
    context-path: /api/v1

##
# EVENT
##
event:
  publisher:
    rate: 5000

##
# USER
##
user:
  event:
    queue:
      user-created: user_created_q

##
# SPRING
##
spring:
  application:
    name: user-api
  ##
  # DATABASE
  ##
  datasource:
    username: userapi
    password: some_password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://user-db:5432/userdb
  ##
  # JPA
  ##
  jpa:
    hibernate:
      ddl-auto: create
  ##
  # RABBITMQ
  ##
  rabbitmq:
    host: outbox-rabbitmq
    port: 5672
    username: admin
    password: admin